// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Company",
    columns: [
      { name: "name", type: "text" },
      { name: "industry", type: "string" },
      { name: "foundedDate", type: "datetime" },
      { name: "privateKey", type: "string" },
      { name: "approved", type: "bool", defaultValue: "false" },
      { name: "user", type: "link", link: { table: "User" } },
    ],
    revLinks: [{ column: "companyId", table: "Customer" }],
  },
  {
    name: "Customer",
    columns: [
      { name: "name", type: "text" },
      { name: "points", type: "float" },
      { name: "companyId", type: "link", link: { table: "Company" } },
      { name: "user", type: "link", link: { table: "User" } },
    ],
  },
  {
    name: "User",
    columns: [
      { name: "name", type: "string" },
      { name: "walletAddress", type: "string", unique: true },
      { name: "role", type: "link", link: { table: "Role" } },
      { name: "email", type: "email" },
      { name: "privateKey", type: "string" },
      { name: "phoneNumber", type: "float" },
    ],
    revLinks: [
      { column: "user", table: "Company" },
      { column: "user", table: "Customer" },
    ],
  },
  {
    name: "Role",
    columns: [
      { name: "name", type: "string" },
      { name: "roleId", type: "int", notNull: true, defaultValue: "1" },
    ],
    revLinks: [{ column: "role", table: "User" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Company = InferredTypes["Company"];
export type CompanyRecord = Company & XataRecord;

export type Customer = InferredTypes["Customer"];
export type CustomerRecord = Customer & XataRecord;

export type User = InferredTypes["User"];
export type UserRecord = User & XataRecord;

export type Role = InferredTypes["Role"];
export type RoleRecord = Role & XataRecord;

export type DatabaseSchema = {
  Company: CompanyRecord;
  Customer: CustomerRecord;
  User: UserRecord;
  Role: RoleRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Arindam-Dawn-s-workspace-8dhin7.us-east-1.xata.sh/db/monet-points",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
