export const CONTRACTS = {
  ELP_CONTRACT: process.env.NEXT_PUBLIC_EIGENLAYER_POINTS_CONTRACT || "",
  ELP_MARKETPLACE_CONTRACT:
    process.env.NEXT_PUBLIC_ELP_MARKETPLACE_CONTRACT || "",
  AIRDROP_CONTRACT: process.env.NEXT_PUBLIC_AIRDROP_CONTRACT || "",
  EIGENLAYER_TOKEN_CONTRACT:
    process.env.NEXT_PUBLIC_EIGENLAYER_TOKEN_CONTRACT || "",
};
