#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git symbolic-ref --short HEAD)

if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "develop" ]; then
  echo "Pushing to $BRANCH_NAME is not allowed."
  exit 1
fi
